blank_issues_enabled: false
contact_links:
  - name: Meta repo (blueprints/specs)
    url: https://github.com/rismun-com/sportbooking-meta
    about: Update specs/blueprints when API contracts change.